_target_: networkts.datasets.abilene.AbileneDataset.from_config
root: 'd:/datasets/traffic_forecasting/preprocessed/Abilene'
topology_adjlist_file: 'graph.adjlist'
nodes_traffic: 'nodes_traffic.csv'
edges_traffic: 'Link_counts.csv'
root_matrix: 'Routing_matrix.csv'
delta_time: 5
period: 288
name: Abilene